In [2]:
from numpy import linalg as LA
from numpy import array
from math import sqrt
import numpy as np


a = array([[1.025,2.09142,-0.313,6.1,5.78],[1.24,-2.435,1.3324,2.67,8.114],[7.01,1.2048,-1.245,5.60931,1.335],\
           [3.214,-6.221,0.9243,-1.693,7.2431],[1.4632,4.1231,3.25,-4.2123,1.9938]])
b = array([1,2,5,3,1])
print (a.T.dot(a) )
print ( LA.eig((a.T.dot(a)))  )
print("------------------------below is svd decomposition---------------------")


u,s,vt = LA.svd(a)


print(vt.T)
print(u)



print("\n------------------------below is solving the linear system---------------------")
x = LA.solve(a,b)
print(x)


print("\n------------------------below is solving the linear system by svd components ---------------------")
diag_eigenvector = array([[1/sqrt(216.37561647),0,0,0,0],\
                          [0,1/sqrt(100.08410035),0,0,0],\
                          [0,0,1/sqrt(49.38342505),0,0],\
                          [0,0,0,1/sqrt(34.17658276),0],\
                          [0,0,0,0,1/sqrt(0.35340114)]])
x_svd = vt.T.dot(diag_eigenvector).dot(u.T).dot(b)
print(x_svd)


[[ 64.19907524  -6.39142058   0.3300012   37.27982374  51.54086156]
 [ -6.39142058  67.45560027   2.25102024   6.17872756 -42.89946272]
 [  0.3300012    2.25102024  14.84011425 -20.59019785  20.51452593]
 [ 37.27982374   6.17872756 -20.59019785  96.41297897  43.74975681]
 [ 51.54086156 -42.89946272  20.51452593  43.74975681 157.46535705]]
(array([216.37561647, 100.08410035,  34.17658276,  49.38342505,
         0.35340114]), array([[-0.37850527,  0.22754263, -0.87840887, -0.18262938,  0.0015737 ],
       [ 0.23120478,  0.49272987,  0.19133505, -0.78356889,  0.23059125],
       [-0.03987157, -0.24071506,  0.03886613, -0.41177417, -0.87715334],
       [-0.39238419,  0.74061481,  0.29263578,  0.32566007, -0.32532163],
       [-0.80481241, -0.31462293,  0.3234849 , -0.27758576,  0.2675688 ]]))
------------------------below is svd decomposition---------------------
[[-0.37850527  0.22754263 -0.18262938  0.87840887 -0.0015737 ]
 [ 0.23120478  0.49272987 -0.78356889 -0.19133505 -0.23059125]
 [